module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    diode_smd: require('./diode_smd'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mounting_hole: require('./mounting_hole'),
    mx: require('./mx'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    pg1316m: require('./pg1316m'),
    pg1316s: require('./pg1316s'),
    promicro: require('./promicro'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),
    xiao_ble: require('./xiao_ble'),
    xiao_flippable: require('./xiao_flippable'),
}